// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BalanceService.proto

package kg.erlanju;

public final class BalanceServiceOuterClass {
  private BalanceServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kg_erlanju_BalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kg_erlanju_BalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kg_erlanju_BalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kg_erlanju_BalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kg_erlanju_BalanceResponse_Wallet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kg_erlanju_BalanceResponse_Wallet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024BalanceService.proto\022\nkg.erlanju\" \n\016Ba" +
      "lanceRequest\022\016\n\006userId\030\001 \001(\005\"\316\001\n\017Balance" +
      "Response\022\016\n\006userId\030\001 \001(\005\0222\n\006wallet\030\002 \003(\013" +
      "2\".kg.erlanju.BalanceResponse.Wallet\032P\n\006" +
      "Wallet\0226\n\010currency\030\001 \001(\0162$.kg.erlanju.Ba" +
      "lanceResponse.Currency\022\016\n\006amount\030\002 \001(\001\"%" +
      "\n\010Currency\022\007\n\003EUR\020\000\022\007\n\003USD\020\001\022\007\n\003GBP\020\0022Y\n" +
      "\016BalanceService\022G\n\014checkBalance\022\032.kg.erl" +
      "anju.BalanceRequest\032\033.kg.erlanju.Balance" +
      "ResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kg_erlanju_BalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kg_erlanju_BalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kg_erlanju_BalanceRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_kg_erlanju_BalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kg_erlanju_BalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kg_erlanju_BalanceResponse_descriptor,
        new java.lang.String[] { "UserId", "Wallet", });
    internal_static_kg_erlanju_BalanceResponse_Wallet_descriptor =
      internal_static_kg_erlanju_BalanceResponse_descriptor.getNestedTypes().get(0);
    internal_static_kg_erlanju_BalanceResponse_Wallet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kg_erlanju_BalanceResponse_Wallet_descriptor,
        new java.lang.String[] { "Currency", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
