// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BalanceService.proto

package kg.erlanju;

/**
 * Protobuf type {@code kg.erlanju.BalanceResponse}
 */
public  final class BalanceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kg.erlanju.BalanceResponse)
    BalanceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BalanceResponse.newBuilder() to construct.
  private BalanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BalanceResponse() {
    userId_ = 0;
    wallet_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BalanceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            userId_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              wallet_ = new java.util.ArrayList<kg.erlanju.BalanceResponse.Wallet>();
              mutable_bitField0_ |= 0x00000002;
            }
            wallet_.add(
                input.readMessage(kg.erlanju.BalanceResponse.Wallet.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        wallet_ = java.util.Collections.unmodifiableList(wallet_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kg.erlanju.BalanceResponse.class, kg.erlanju.BalanceResponse.Builder.class);
  }

  /**
   * Protobuf enum {@code kg.erlanju.BalanceResponse.Currency}
   */
  public enum Currency
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EUR = 0;</code>
     */
    EUR(0),
    /**
     * <code>USD = 1;</code>
     */
    USD(1),
    /**
     * <code>GBP = 2;</code>
     */
    GBP(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EUR = 0;</code>
     */
    public static final int EUR_VALUE = 0;
    /**
     * <code>USD = 1;</code>
     */
    public static final int USD_VALUE = 1;
    /**
     * <code>GBP = 2;</code>
     */
    public static final int GBP_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Currency valueOf(int value) {
      return forNumber(value);
    }

    public static Currency forNumber(int value) {
      switch (value) {
        case 0: return EUR;
        case 1: return USD;
        case 2: return GBP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Currency>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Currency> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Currency>() {
            public Currency findValueByNumber(int number) {
              return Currency.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return kg.erlanju.BalanceResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Currency[] VALUES = values();

    public static Currency valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Currency(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kg.erlanju.BalanceResponse.Currency)
  }

  public interface WalletOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kg.erlanju.BalanceResponse.Wallet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.kg.erlanju.BalanceResponse.Currency currency = 1;</code>
     */
    int getCurrencyValue();
    /**
     * <code>.kg.erlanju.BalanceResponse.Currency currency = 1;</code>
     */
    kg.erlanju.BalanceResponse.Currency getCurrency();

    /**
     * <code>double amount = 2;</code>
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code kg.erlanju.BalanceResponse.Wallet}
   */
  public  static final class Wallet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kg.erlanju.BalanceResponse.Wallet)
      WalletOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Wallet.newBuilder() to construct.
    private Wallet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Wallet() {
      currency_ = 0;
      amount_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Wallet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              currency_ = rawValue;
              break;
            }
            case 17: {

              amount_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_Wallet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_Wallet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kg.erlanju.BalanceResponse.Wallet.class, kg.erlanju.BalanceResponse.Wallet.Builder.class);
    }

    public static final int CURRENCY_FIELD_NUMBER = 1;
    private int currency_;
    /**
     * <code>.kg.erlanju.BalanceResponse.Currency currency = 1;</code>
     */
    public int getCurrencyValue() {
      return currency_;
    }
    /**
     * <code>.kg.erlanju.BalanceResponse.Currency currency = 1;</code>
     */
    public kg.erlanju.BalanceResponse.Currency getCurrency() {
      kg.erlanju.BalanceResponse.Currency result = kg.erlanju.BalanceResponse.Currency.valueOf(currency_);
      return result == null ? kg.erlanju.BalanceResponse.Currency.UNRECOGNIZED : result;
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private double amount_;
    /**
     * <code>double amount = 2;</code>
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currency_ != kg.erlanju.BalanceResponse.Currency.EUR.getNumber()) {
        output.writeEnum(1, currency_);
      }
      if (amount_ != 0D) {
        output.writeDouble(2, amount_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currency_ != kg.erlanju.BalanceResponse.Currency.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, currency_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kg.erlanju.BalanceResponse.Wallet)) {
        return super.equals(obj);
      }
      kg.erlanju.BalanceResponse.Wallet other = (kg.erlanju.BalanceResponse.Wallet) obj;

      boolean result = true;
      result = result && currency_ == other.currency_;
      result = result && (
          java.lang.Double.doubleToLongBits(getAmount())
          == java.lang.Double.doubleToLongBits(
              other.getAmount()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + currency_;
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kg.erlanju.BalanceResponse.Wallet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kg.erlanju.BalanceResponse.Wallet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kg.erlanju.BalanceResponse.Wallet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kg.erlanju.BalanceResponse.Wallet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kg.erlanju.BalanceResponse.Wallet)
        kg.erlanju.BalanceResponse.WalletOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_Wallet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_Wallet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kg.erlanju.BalanceResponse.Wallet.class, kg.erlanju.BalanceResponse.Wallet.Builder.class);
      }

      // Construct using kg.erlanju.BalanceResponse.Wallet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        currency_ = 0;

        amount_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_Wallet_descriptor;
      }

      public kg.erlanju.BalanceResponse.Wallet getDefaultInstanceForType() {
        return kg.erlanju.BalanceResponse.Wallet.getDefaultInstance();
      }

      public kg.erlanju.BalanceResponse.Wallet build() {
        kg.erlanju.BalanceResponse.Wallet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kg.erlanju.BalanceResponse.Wallet buildPartial() {
        kg.erlanju.BalanceResponse.Wallet result = new kg.erlanju.BalanceResponse.Wallet(this);
        result.currency_ = currency_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kg.erlanju.BalanceResponse.Wallet) {
          return mergeFrom((kg.erlanju.BalanceResponse.Wallet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kg.erlanju.BalanceResponse.Wallet other) {
        if (other == kg.erlanju.BalanceResponse.Wallet.getDefaultInstance()) return this;
        if (other.currency_ != 0) {
          setCurrencyValue(other.getCurrencyValue());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kg.erlanju.BalanceResponse.Wallet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kg.erlanju.BalanceResponse.Wallet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int currency_ = 0;
      /**
       * <code>.kg.erlanju.BalanceResponse.Currency currency = 1;</code>
       */
      public int getCurrencyValue() {
        return currency_;
      }
      /**
       * <code>.kg.erlanju.BalanceResponse.Currency currency = 1;</code>
       */
      public Builder setCurrencyValue(int value) {
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.kg.erlanju.BalanceResponse.Currency currency = 1;</code>
       */
      public kg.erlanju.BalanceResponse.Currency getCurrency() {
        kg.erlanju.BalanceResponse.Currency result = kg.erlanju.BalanceResponse.Currency.valueOf(currency_);
        return result == null ? kg.erlanju.BalanceResponse.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.kg.erlanju.BalanceResponse.Currency currency = 1;</code>
       */
      public Builder setCurrency(kg.erlanju.BalanceResponse.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        currency_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.kg.erlanju.BalanceResponse.Currency currency = 1;</code>
       */
      public Builder clearCurrency() {
        
        currency_ = 0;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 2;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kg.erlanju.BalanceResponse.Wallet)
    }

    // @@protoc_insertion_point(class_scope:kg.erlanju.BalanceResponse.Wallet)
    private static final kg.erlanju.BalanceResponse.Wallet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kg.erlanju.BalanceResponse.Wallet();
    }

    public static kg.erlanju.BalanceResponse.Wallet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Wallet>
        PARSER = new com.google.protobuf.AbstractParser<Wallet>() {
      public Wallet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Wallet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Wallet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Wallet> getParserForType() {
      return PARSER;
    }

    public kg.erlanju.BalanceResponse.Wallet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int USERID_FIELD_NUMBER = 1;
  private int userId_;
  /**
   * <code>int32 userId = 1;</code>
   */
  public int getUserId() {
    return userId_;
  }

  public static final int WALLET_FIELD_NUMBER = 2;
  private java.util.List<kg.erlanju.BalanceResponse.Wallet> wallet_;
  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  public java.util.List<kg.erlanju.BalanceResponse.Wallet> getWalletList() {
    return wallet_;
  }
  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  public java.util.List<? extends kg.erlanju.BalanceResponse.WalletOrBuilder> 
      getWalletOrBuilderList() {
    return wallet_;
  }
  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  public int getWalletCount() {
    return wallet_.size();
  }
  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  public kg.erlanju.BalanceResponse.Wallet getWallet(int index) {
    return wallet_.get(index);
  }
  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  public kg.erlanju.BalanceResponse.WalletOrBuilder getWalletOrBuilder(
      int index) {
    return wallet_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0) {
      output.writeInt32(1, userId_);
    }
    for (int i = 0; i < wallet_.size(); i++) {
      output.writeMessage(2, wallet_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, userId_);
    }
    for (int i = 0; i < wallet_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, wallet_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kg.erlanju.BalanceResponse)) {
      return super.equals(obj);
    }
    kg.erlanju.BalanceResponse other = (kg.erlanju.BalanceResponse) obj;

    boolean result = true;
    result = result && (getUserId()
        == other.getUserId());
    result = result && getWalletList()
        .equals(other.getWalletList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    if (getWalletCount() > 0) {
      hash = (37 * hash) + WALLET_FIELD_NUMBER;
      hash = (53 * hash) + getWalletList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kg.erlanju.BalanceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kg.erlanju.BalanceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kg.erlanju.BalanceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kg.erlanju.BalanceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kg.erlanju.BalanceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kg.erlanju.BalanceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kg.erlanju.BalanceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kg.erlanju.BalanceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kg.erlanju.BalanceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kg.erlanju.BalanceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kg.erlanju.BalanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kg.erlanju.BalanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kg.erlanju.BalanceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kg.erlanju.BalanceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kg.erlanju.BalanceResponse)
      kg.erlanju.BalanceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kg.erlanju.BalanceResponse.class, kg.erlanju.BalanceResponse.Builder.class);
    }

    // Construct using kg.erlanju.BalanceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getWalletFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      userId_ = 0;

      if (walletBuilder_ == null) {
        wallet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        walletBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kg.erlanju.BalanceServiceOuterClass.internal_static_kg_erlanju_BalanceResponse_descriptor;
    }

    public kg.erlanju.BalanceResponse getDefaultInstanceForType() {
      return kg.erlanju.BalanceResponse.getDefaultInstance();
    }

    public kg.erlanju.BalanceResponse build() {
      kg.erlanju.BalanceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kg.erlanju.BalanceResponse buildPartial() {
      kg.erlanju.BalanceResponse result = new kg.erlanju.BalanceResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.userId_ = userId_;
      if (walletBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          wallet_ = java.util.Collections.unmodifiableList(wallet_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.wallet_ = wallet_;
      } else {
        result.wallet_ = walletBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kg.erlanju.BalanceResponse) {
        return mergeFrom((kg.erlanju.BalanceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kg.erlanju.BalanceResponse other) {
      if (other == kg.erlanju.BalanceResponse.getDefaultInstance()) return this;
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (walletBuilder_ == null) {
        if (!other.wallet_.isEmpty()) {
          if (wallet_.isEmpty()) {
            wallet_ = other.wallet_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureWalletIsMutable();
            wallet_.addAll(other.wallet_);
          }
          onChanged();
        }
      } else {
        if (!other.wallet_.isEmpty()) {
          if (walletBuilder_.isEmpty()) {
            walletBuilder_.dispose();
            walletBuilder_ = null;
            wallet_ = other.wallet_;
            bitField0_ = (bitField0_ & ~0x00000002);
            walletBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWalletFieldBuilder() : null;
          } else {
            walletBuilder_.addAllMessages(other.wallet_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kg.erlanju.BalanceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kg.erlanju.BalanceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int userId_ ;
    /**
     * <code>int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 userId = 1;</code>
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 userId = 1;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<kg.erlanju.BalanceResponse.Wallet> wallet_ =
      java.util.Collections.emptyList();
    private void ensureWalletIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        wallet_ = new java.util.ArrayList<kg.erlanju.BalanceResponse.Wallet>(wallet_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kg.erlanju.BalanceResponse.Wallet, kg.erlanju.BalanceResponse.Wallet.Builder, kg.erlanju.BalanceResponse.WalletOrBuilder> walletBuilder_;

    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public java.util.List<kg.erlanju.BalanceResponse.Wallet> getWalletList() {
      if (walletBuilder_ == null) {
        return java.util.Collections.unmodifiableList(wallet_);
      } else {
        return walletBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public int getWalletCount() {
      if (walletBuilder_ == null) {
        return wallet_.size();
      } else {
        return walletBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public kg.erlanju.BalanceResponse.Wallet getWallet(int index) {
      if (walletBuilder_ == null) {
        return wallet_.get(index);
      } else {
        return walletBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public Builder setWallet(
        int index, kg.erlanju.BalanceResponse.Wallet value) {
      if (walletBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWalletIsMutable();
        wallet_.set(index, value);
        onChanged();
      } else {
        walletBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public Builder setWallet(
        int index, kg.erlanju.BalanceResponse.Wallet.Builder builderForValue) {
      if (walletBuilder_ == null) {
        ensureWalletIsMutable();
        wallet_.set(index, builderForValue.build());
        onChanged();
      } else {
        walletBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public Builder addWallet(kg.erlanju.BalanceResponse.Wallet value) {
      if (walletBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWalletIsMutable();
        wallet_.add(value);
        onChanged();
      } else {
        walletBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public Builder addWallet(
        int index, kg.erlanju.BalanceResponse.Wallet value) {
      if (walletBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWalletIsMutable();
        wallet_.add(index, value);
        onChanged();
      } else {
        walletBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public Builder addWallet(
        kg.erlanju.BalanceResponse.Wallet.Builder builderForValue) {
      if (walletBuilder_ == null) {
        ensureWalletIsMutable();
        wallet_.add(builderForValue.build());
        onChanged();
      } else {
        walletBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public Builder addWallet(
        int index, kg.erlanju.BalanceResponse.Wallet.Builder builderForValue) {
      if (walletBuilder_ == null) {
        ensureWalletIsMutable();
        wallet_.add(index, builderForValue.build());
        onChanged();
      } else {
        walletBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public Builder addAllWallet(
        java.lang.Iterable<? extends kg.erlanju.BalanceResponse.Wallet> values) {
      if (walletBuilder_ == null) {
        ensureWalletIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, wallet_);
        onChanged();
      } else {
        walletBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public Builder clearWallet() {
      if (walletBuilder_ == null) {
        wallet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        walletBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public Builder removeWallet(int index) {
      if (walletBuilder_ == null) {
        ensureWalletIsMutable();
        wallet_.remove(index);
        onChanged();
      } else {
        walletBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public kg.erlanju.BalanceResponse.Wallet.Builder getWalletBuilder(
        int index) {
      return getWalletFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public kg.erlanju.BalanceResponse.WalletOrBuilder getWalletOrBuilder(
        int index) {
      if (walletBuilder_ == null) {
        return wallet_.get(index);  } else {
        return walletBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public java.util.List<? extends kg.erlanju.BalanceResponse.WalletOrBuilder> 
         getWalletOrBuilderList() {
      if (walletBuilder_ != null) {
        return walletBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(wallet_);
      }
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public kg.erlanju.BalanceResponse.Wallet.Builder addWalletBuilder() {
      return getWalletFieldBuilder().addBuilder(
          kg.erlanju.BalanceResponse.Wallet.getDefaultInstance());
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public kg.erlanju.BalanceResponse.Wallet.Builder addWalletBuilder(
        int index) {
      return getWalletFieldBuilder().addBuilder(
          index, kg.erlanju.BalanceResponse.Wallet.getDefaultInstance());
    }
    /**
     * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
     */
    public java.util.List<kg.erlanju.BalanceResponse.Wallet.Builder> 
         getWalletBuilderList() {
      return getWalletFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kg.erlanju.BalanceResponse.Wallet, kg.erlanju.BalanceResponse.Wallet.Builder, kg.erlanju.BalanceResponse.WalletOrBuilder> 
        getWalletFieldBuilder() {
      if (walletBuilder_ == null) {
        walletBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kg.erlanju.BalanceResponse.Wallet, kg.erlanju.BalanceResponse.Wallet.Builder, kg.erlanju.BalanceResponse.WalletOrBuilder>(
                wallet_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        wallet_ = null;
      }
      return walletBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kg.erlanju.BalanceResponse)
  }

  // @@protoc_insertion_point(class_scope:kg.erlanju.BalanceResponse)
  private static final kg.erlanju.BalanceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kg.erlanju.BalanceResponse();
  }

  public static kg.erlanju.BalanceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BalanceResponse>
      PARSER = new com.google.protobuf.AbstractParser<BalanceResponse>() {
    public BalanceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BalanceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BalanceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BalanceResponse> getParserForType() {
    return PARSER;
  }

  public kg.erlanju.BalanceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

