// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DepositService.proto

package kg.erlanju;

public interface DepositRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kg.erlanju.DepositRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   */
  int getUserId();

  /**
   * <code>double amount = 2;</code>
   */
  double getAmount();

  /**
   * <code>.kg.erlanju.DepositRequest.Currency currency = 3;</code>
   */
  int getCurrencyValue();
  /**
   * <code>.kg.erlanju.DepositRequest.Currency currency = 3;</code>
   */
  kg.erlanju.DepositRequest.Currency getCurrency();
}
