// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package kg.erlanju;

public final class HelloService {
  private HelloService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kg_erlanju_DepositRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kg_erlanju_DepositRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kg_erlanju_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kg_erlanju_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HelloService.proto\022\nkg.erlanju\"\216\001\n\016Dep" +
      "ositRequest\022\016\n\006userId\030\001 \001(\005\022\016\n\006amount\030\002 " +
      "\001(\001\0225\n\010currency\030\003 \001(\0162#.kg.erlanju.Depos" +
      "itRequest.Currency\"%\n\010Currency\022\007\n\003EUR\020\000\022" +
      "\007\n\003USD\020\001\022\007\n\003GBP\020\002\"\017\n\rHelloResponse2R\n\016De" +
      "positService\022@\n\007deposit\022\032.kg.erlanju.Dep" +
      "ositRequest\032\031.kg.erlanju.HelloResponseB\002" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kg_erlanju_DepositRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kg_erlanju_DepositRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kg_erlanju_DepositRequest_descriptor,
        new java.lang.String[] { "UserId", "Amount", "Currency", });
    internal_static_kg_erlanju_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kg_erlanju_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kg_erlanju_HelloResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
