// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package kg.erlanju;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kg.erlanju.HelloResponse)
    com.google.protobuf.MessageOrBuilder {
}
