// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WithdrawService.proto

package kg.erlanju;

public interface WithdrawResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kg.erlanju.WithdrawResponse)
    com.google.protobuf.MessageOrBuilder {
}
