// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BalanceService.proto

package kg.erlanju;

public interface BalanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kg.erlanju.BalanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   */
  int getUserId();

  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  java.util.List<kg.erlanju.BalanceResponse.Wallet> 
      getWalletList();
  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  kg.erlanju.BalanceResponse.Wallet getWallet(int index);
  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  int getWalletCount();
  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  java.util.List<? extends kg.erlanju.BalanceResponse.WalletOrBuilder> 
      getWalletOrBuilderList();
  /**
   * <code>repeated .kg.erlanju.BalanceResponse.Wallet wallet = 2;</code>
   */
  kg.erlanju.BalanceResponse.WalletOrBuilder getWalletOrBuilder(
      int index);
}
