// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BalanceService.proto

package kg.erlanju;

public interface BalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kg.erlanju.BalanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   */
  int getUserId();
}
