// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DepositService.proto

package kg.erlanju;

public interface DepositResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kg.erlanju.DepositResponse)
    com.google.protobuf.MessageOrBuilder {
}
